language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: yMcZgqIKIUF1jpkhlxXAbK9NTcoLRNM8RlKmRz1TBv30VFc7YL3Fe7yYlIydjJdF0yQ4gdNv8cfWRruHc4AYQnGRZ5tSOmcSu6EMUOIypCORBRTavC4wn4zOsIypQgYjXi5uKAh8otgiAGiOk1UVUGzbLrb7dbQV5S1wzZmlxh99Fq/IcaAHQxP0R9FL//qcPPEYxNTIpBg62nGx5FuUI/vQmtmTvPpMl8edftOoLYIL370/0180faKK3WCc05nQo3bFgXP3YEzHQpXe4VI1mBASQxyqZOziF02q9wGbCB6KmE8yYU4iH5ENbXKqG6v8bhXZf1VoYAU/C4WYi9wB4TLlQvnDCsdG3EhZy3W/wE2Bgjz3xDkXyGVx1Lw15GP4x7oh7qiQJFT482YBF5F0dBupruDeTgx/jFcnuv+H+M28rZXbthtddacdiWRmy0dp+fzK6oyA7FSEAuWIxB1owE82uQYHYT2wbhTr9nws6XR6c8vbvalgVeKB19eYjbAcurdMkj+X4NFHJUOOFpzadxwZ/AousHz2o6K6v9w3gLtCSkCJ+weA+zkSlVeZ9aovSMkPL4cpmRsUa6GgW3kzvoCJnkHXB7scDesgvmcLFsZcDSJnHD/LVMPc1xaaw74xGkHge6L5rdin3G+TW1GJAKIsgTkv5/1lzPh71qu3eBU=
  on:
    tags: true
    repo: DEGJS/dialogLoader
